### Insert
post http://localhost:4000/v1/course
Content-Type: application/json

{
    "title": "Microfrontends con Angular"
}

### Get all
get http://localhost:4000/v1/course

### Get by id
get http://localhost:4000/v1/course/93e3b4c0-b826-4ef5-bfe4-7de290bc29dd

### Update
put http://localhost:4000/v1/course/9c132c06-1390-428c-b9f4-2d277cc0d922
Content-Type: application/json

{
    "title": "This is a course updated"
}

### Update
put http://localhost:4000/v2/course/9c132c06-1390-428c-b9f4-2d277cc0d922
Content-Type: application/json

{
    "title": "This is a course updated"
}

### Delete
delete http://localhost:4000/v1/course/06528a82-2f3d-4de2-88a0-ada9c34e2ce0

### Page
get http://localhost:4000/v1/course/page?page=3&limit=10
