### Insert
post http://localhost:4000/v1/course
Content-Type: application/json

{
    "title": "Microfrontends con Angular 18 y React 23"
}

### Get all
get http://localhost:4000/v1/course

### Get by id
get http://localhost:4000/v1/course/93e3b4c0-b826-4ef5-bfe4-7de290bc29dd

### Update
put http://localhost:4000/v1/course/37695e76-9d74-408b-903d-4de7113442f0
Content-Type: application/json

{
    "title": "This is a course updated with Observability222555"
}

### Update
put http://localhost:4000/v2/course/aa14f384-5f64-4273-b210-c4fff378b8e7
Content-Type: application/json

{
    "title": "This is a course updated4"
}

### Delete
delete http://localhost:4000/v1/course/37695e76-9d74-408b-903d-4de7113442f0

### Page
get http://localhost:4000/v1/course/page?page=3&limit=10
